title: Septima Vector
description: >- # this means to ignore newlines until "baseurl:"
  The only real security that a man can have in this world is a reserve 
  of knowledge, experience and ability. ~Henry Ford
baseurl: '/posts'
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
